// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mesajlasmaAPI.Data;

#nullable disable

namespace mesajlasmaAPI.Migrations
{
    [DbContext(typeof(mesajlasmadbcontext))]
    partial class mesajlasmadbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("mesajlasmaAPI.Data.Models.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grup");
                });

            modelBuilder.Entity("mesajlasmaAPI.Data.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("mesajlasmaAPI.Data.Models.Mesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlanId")
                        .HasColumnType("int");

                    b.Property<int>("GonderenId")
                        .HasColumnType("int");

                    b.Property<int?>("GrupId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GrupId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Mesaj");
                });

            modelBuilder.Entity("mesajlasmaAPI.Data.Models.Kullanici", b =>
                {
                    b.HasOne("mesajlasmaAPI.Data.Models.Grup", "Grup")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("GrupId");

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("mesajlasmaAPI.Data.Models.Mesaj", b =>
                {
                    b.HasOne("mesajlasmaAPI.Data.Models.Grup", "Grup")
                        .WithMany("Mesajlar")
                        .HasForeignKey("GrupId");

                    b.HasOne("mesajlasmaAPI.Data.Models.Kullanici", null)
                        .WithMany("Mesajlar")
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("mesajlasmaAPI.Data.Models.Grup", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("Mesajlar");
                });

            modelBuilder.Entity("mesajlasmaAPI.Data.Models.Kullanici", b =>
                {
                    b.Navigation("Mesajlar");
                });
#pragma warning restore 612, 618
        }
    }
}
